name: CMake

on:
  push:
    branches: [ main, system ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  # Build and benchmark on Ubuntu.
  build-and-benchmark-ubuntu:
    runs-on: ubuntu-latest
    env:
      CXX: clang++
      CC: clang

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
  
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
  
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
  
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --rerun-failed --output-on-failure
  
    - name: Benchmark
      working-directory: ${{github.workspace}}/build
      run: ./benchmark/Benchmark

  # Build and benchmark on MacOS.
  build-and-benchmark-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
  
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
  
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
  
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --rerun-failed --output-on-failure
  
    - name: Benchmark
      working-directory: ${{github.workspace}}/build
      run: ./benchmark/Benchmark
      
  # Build and benchmark on Windows.
  build-and-benchmark-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --rerun-failed --output-on-failure

    - name: Benchmark
      working-directory: ${{github.workspace}}/build
      run: ./benchmark/Release/Benchmark.exe